name: Unzip Files

on: [push]

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install unzip
      run: sudo apt-get install -y unzip

    - name: Unzip file
      run: unzip -o https://github.com/loongyowl/serenevox.com/blob/main/twine/twine-2.8.1-web.zip -d https://github.com/loongyowl/serenevox.com/blob/main/twine/

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Unzip files"
        git push
